# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 888ceb5e2928e3906f69f271b0e5a5dce47563fd2d3fd9d47eb54788125d7d1339753b96012e3ea80c41c5abeb4c4a98154db7b77b3099c39df8dc809a1d3bd9

test:
  secret_key_base: e8981ccdf874f22bcc50aec5abde1e76e2c5527909924f8b70c203abf5f0578763b37ddb7dd5ff48c7ea9b7106b1fda6b9436b1abef14e267c0df7af2a865e71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
